#! /usr/bin/env python
"""CIU -- Compose Image Updater main script"""

from docker_tag_updater import skopeo, parser


args = parser.ciu_parser.parse_args()


def main():
    registry, image, tag = skopeo.parse(args.image)
    skopeo_tag = skopeo.image_version(
        image, registry=registry, base_tag=args.tag, verbose=args.verbose
    )

    newest_tag = skopeo.compare_versions(
        source_ver=tag, target_ver=skopeo_tag, rule=args.rule
    )
    if args.verbose:
        print("The most up-to-date tagged image is:")
    print(args.image.replace(tag, newest_tag))


if __name__ == "__main__":
    main()
