#! /usr/bin/env python
"""image-version-checker

Check for new versions of a container image.
"""
import sys
from docker_tag_updater import skopeo, parser


args = parser.ivc_parser.parse_args()


def main():
    registry, image, tag = skopeo.parse(args.image)
    if args.parse:
        print(f"{registry} {image} {tag}")
        sys.exit(0)

    skopeo_tag = skopeo.image_version(
        image, registry=registry, base_tag=args.tag, verbose=args.verbose
    )

    newest_tag = skopeo.compare_versions(
        source_ver=tag, target_ver=skopeo_tag, rule=args.rule
    )
    if args.verbose:
        print("The most up-to-date tagged image is:")
    print(args.image.replace(tag, newest_tag))


if __name__ == "__main__":
    main()
